DROP TABLE IF EXISTS fixtures;
DROP TABLE IF EXISTS athletes;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS team_follows;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS otp_codes;
DROP TABLE IF EXISTS accounts;
