import type { Team } from '../types'

export const TEAMS: Team[] = [
  {
    id: 'team-nairobi-thunder',
    name: 'Nairobi Thunder FC',
    county: 'Nairobi',
    sport: 'football',
    category: 'standard',
    crestColor: '#14532D',
    followerCount: 842,
  },
  {
    id: 'team-kibera-rangers',
    name: 'Kibera Rangers',
    county: 'Nairobi',
    sport: 'football',
    category: 'standard',
    crestColor: '#B45309',
    followerCount: 611,
  },
  {
    id: 'team-kisumu-lakers',
    name: 'Kisumu Lakers',
    county: 'Kisumu',
    sport: 'basketball',
    category: 'standard',
    crestColor: '#1D4ED8',
    followerCount: 398,
  },
  {
    id: 'team-nyalenda-queens',
    name: 'Nyalenda Queens',
    county: 'Kisumu',
    sport: 'netball',
    category: 'standard',
    crestColor: '#BE185D',
    followerCount: 275,
  },
  {
    id: 'team-mombasa-sharks',
    name: 'Mombasa Sharks RFC',
    county: 'Mombasa',
    sport: 'rugby',
    category: 'standard',
    crestColor: '#0E7490',
    followerCount: 520,
  },
  {
    id: 'team-tudor-tridents',
    name: 'Tudor Tridents',
    county: 'Mombasa',
    sport: 'volleyball',
    category: 'standard',
    crestColor: '#7C3AED',
    followerCount: 189,
  },
  {
    id: 'team-nakuru-warriors',
    name: 'Nakuru Warriors',
    county: 'Nakuru',
    sport: 'football',
    category: 'adaptive',
    disabilityCategory: 'Amputee football',
    crestColor: '#B91C1C',
    followerCount: 334,
  },
  {
    id: 'team-rift-valley-blazers',
    name: 'Rift Valley Blazers',
    county: 'Nakuru',
    sport: 'athletics',
    category: 'standard',
    crestColor: '#CA8A04',
    followerCount: 447,
  },
  {
    id: 'team-eldoret-eagles',
    name: 'Eldoret Eagles',
    county: 'Uasin Gishu',
    sport: 'football',
    category: 'standard',
    crestColor: '#166534',
    followerCount: 703,
  },
  {
    id: 'team-eldoret-wheelchair-hoopers',
    name: 'Eldoret Wheelchair Hoopers',
    county: 'Uasin Gishu',
    sport: 'basketball',
    category: 'adaptive',
    disabilityCategory: 'Wheelchair basketball',
    crestColor: '#0F766E',
    followerCount: 156,
  },
  {
    id: 'team-machakos-hills',
    name: 'Machakos Hills FC',
    county: 'Machakos',
    sport: 'football',
    category: 'standard',
    crestColor: '#9A3412',
    followerCount: 288,
  },
  {
    id: 'team-kitale-comets',
    name: 'Kitale Comets',
    county: 'Trans Nzoia',
    sport: 'volleyball',
    category: 'standard',
    crestColor: '#4338CA',
    followerCount: 143,
  },
  {
    id: 'team-kakamega-forest-runners',
    name: 'Kakamega Forest Runners',
    county: 'Kakamega',
    sport: 'athletics',
    category: 'standard',
    crestColor: '#15803D',
    followerCount: 231,
  },
  {
    id: 'team-nyeri-blind-strikers',
    name: 'Nyeri Blind Strikers',
    county: 'Nyeri',
    sport: 'football',
    category: 'adaptive',
    disabilityCategory: 'Blind football (5-a-side)',
    crestColor: '#374151',
    followerCount: 97,
  },
]
